# Steps by Step
---

- name: Add OpenTofu user
  shell: pveum user add "{{ opentofu_user }}" --comment "OpenTofu account"
  register: add_opentofu_user
  changed_when: "'created user' in add_opentofu_user.stdout"

- name: Add OpenTofu role
  shell: pveum role add tofu -privs "Datastore.AllocateSpace Datastore.Audit Pool.Allocate Sys.Audit Sys.Console Sys.Modify VM.Allocate VM.Audit VM.Clone VM.Config.CDROM VM.Config.Cloudinit VM.Config.CPU VM.Config.Disk VM.Config.HWType VM.Config.Memory VM.Config.Network VM.Config.Options VM.Migrate VM.Monitor VM.PowerMgmt SDN.Use"
  register: add_opentofu_role
  changed_when: false

- name: Assign role to OpenTofu user
  shell: pveum aclmod / -user tofu@pam -role tofu
  when: add_opentofu_role is succeeded
  register: assign_role
  changed_when: false

- name: Add token for OpenTofu user
  shell: pveum user token add tofu@pam fortofu -expire 0 -privsep 0 -comment "tofu token"
  when: assign_role is succeeded
  register: add_token
  changed_when: false

- name: Extract token value
  set_fact:
    token_value: "{{ add_token.stdout_lines | select('search', '^│\\s*value\\s*│') | map('regex_replace', '^│\\s*value\\s*│\\s*(\\S+)\\s*│$', '\\1') | list | first }}"

- name: Debug - Output of token value
  debug:
    msg: "Token value: {{ token_value }}"
